spring.application.name=bankapi

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=bankdb

server.port=8080

mongodb+srv://tarrington2003_db_user:vuHuvn3LggK9ZPsU@cluster0.g4r7cmr.mongodb.net/